# Generated by Django 5.2.8 on 2025-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('provider_id', models.CharField(db_index=True, max_length=100)),
                ('diagnosis_code', models.CharField(db_index=True, max_length=50)),
                ('diagnosis_description', models.TextField(blank=True, null=True)),
                ('procedure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('procedure_description', models.TextField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim_date', models.DateField()),
                ('service_date', models.DateField(blank=True, null=True)),
                ('fraud_score', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fraud_score', '-claim_date'],
                'indexes': [models.Index(fields=['fraud_score'], name='claims_clai_fraud_s_878aed_idx'), models.Index(fields=['claim_date'], name='claims_clai_claim_d_df9090_idx'), models.Index(fields=['patient_id', 'claim_date'], name='claims_clai_patient_d75582_idx'), models.Index(fields=['provider_id', 'claim_date'], name='claims_clai_provide_ed6faf_idx')],
            },
        ),
    ]
